

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app
    container_name: my-container
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 
    restart: unless-stopped